###
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "author": "Veres Attila",
  "title": "Black Maybe",
  "isbn": "1234123412341",
  "numberOfPages": 341,
  "yearOfPublish": 2022,
  "genre": "HORROR"
}

###
POST http://localhost:8080/api/books
Content-Type: application/json

{
"author": "Jonathan Franzen",
"title": "Crossroads",
"isbn": "3213213213211",
"numberOfPages": 841,
"yearOfPublish": 2021,
"genre": "CONTEMPORARY"
}

###
DELETE http://localhost:8080/api/books/3

###
GET http://localhost:8080/api/books?searchTerm=ttila
Accept: application/json

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "asdfasd",
  "email": "murakami@haruki.jp",
  "password": "Aadsa123##"
}

###
POST http://localhost:8080/api/users/3/shelves
Content-Type: application/json

{
  "shelfName": "favourites"
}

###
GET http://localhost:8080/api/users/1/shelves
Accept: application/json

###
GET http://localhost:8080/api/users/1/shelves?shelfName=kami
Accept: application/json