###
POST http://localhost:8080/api/books
Content-Type: application/json

{
  "author": "Veres Attila",
  "title": "Black Maybe",
  "isbn": "12341sd23",
  "numberOfPages": 341,
  "yearOfPublish": 2022,
  "genre": "HORROR"
}

###
GET http://localhost:8080/api/books?searchTerm=Maybe
Accept: application/json

###
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "username": "asdfasd",
  "email": "murakami@haruki.jp",
  "password": "Aadsa123##"
}

###
POST http://localhost:8080/api/users/3/shelves
Content-Type: application/json

{
  "shelfName": "favourites"
}

###
GET http://localhost:8080/api/users/1/shelves
Accept: application/json

###
GET http://localhost:8080/api/users/1/shelves?shelfName=kami
Accept: application/json